
import type { Translations } from './types';
import { Level } from './types';

export const BANK_TEXT: Record<Level, string[]> = {
  [Level.Letters]: [
    "ا","ب","ت","ث","ج","ح","خ","د","ذ","ر","ز","س","ش","ص","ض","ط","ظ","ع","غ","ف","ق","ك","ل","م","ن","ه","و","ي"
  ],
  [Level.Easy]: [
    "اللّه", "كتاب", "مسجد", "نور", "سلام", "إيمان", "علم", "قلب", "صبر", "رزق"
  ],
  [Level.Medium]: [
    "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
    "السَّلَامُ عَلَيْكُمْ وَرَحْمَةُ اللَّهِ",
    "الحَمْدُ لِلَّهِ رَبِّ العَالَمِينَ",
    "اللَّهُ نُورُ السَّمَاوَاتِ وَالأَرْضِ",
    "رَبِّ زِدْنِي عِلْمًا"
  ],
  [Level.Hard]: [
    "وَإِنَّكَ لَعَلَىٰ خُلُقٍ عَظِيمٍ",
    "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ",
    "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
    "رَبَّنَا اغْفِرْ لَنَا ذُنُوبَنَا وَإِسْرَافَنَا فِي أَمْرِنَا"
  ]
};

export const TRANSLATIONS: Translations = {
  id: {
    title: "Latihan Mengetik Arab",
    start: "Mulai",
    next: "Teks Berikutnya",
    reset: "Reset",
    stats: "Statistik",
    leaderboardTitle: "Leaderboard Lokal",
    leaderboardMuted: "Top 3 skor terbaik (tersimpan di perangkat ini)",
    playerPlaceholder: "Nama pemain",
    level_letters: "Huruf — Latihan Huruf",
    level_easy: "Mudah — Kata Pendek",
    level_medium: "Sedang — Kalimat Pendek",
    level_hard: "Sulit — Ayat/Doa",
    dur_60: "60 detik",
    dur_120: "120 detik",
    dur_180: "180 detik",
    modalTitle: "Ringkasan Sesi",
    lblPlayer: "Pemain:",
    lblLevel: "Level:",
    lblDuration: "Durasi:",
    lblWords: "Kata benar:",
    lblAccuracy: "Akurasi:",
    lblKPM: "KPM:",
    lblCPM: "CPM:",
    lblScore: "Skor:",
    lblNote: "Skor menggabungkan akurasi, kecepatan, dan jumlah kata benar.",
    modalClose: "Tutup",
    placeholder: "Ketik teks di atas…",
    dark: "Gelap",
    light: "Terang",
    timeLeft: "Sisa Waktu",
    accuracy: "Akurasi",
    cpm: "KPM",
    correctWords: "Kata Benar",
  },
  en: {
    title: "Arabic Typing Practice",
    start: "Start",
    next: "Next Text",
    reset: "Reset",
    stats: "Statistics",
    leaderboardTitle: "Local Leaderboard",
    leaderboardMuted: "Top 3 best scores (stored on this device)",
    playerPlaceholder: "Player name",
    level_letters: "Letters — Letters Practice",
    level_easy: "Easy — Short words",
    level_medium: "Medium — Short sentences",
    level_hard: "Hard — Verses/Prayers",
    dur_60: "60 sec",
    dur_120: "120 sec",
    dur_180: "180 sec",
    modalTitle: "Session Summary",
    lblPlayer: "Player:",
    lblLevel: "Level:",
    lblDuration: "Duration:",
    lblWords: "Correct:",
    lblAccuracy: "Accuracy:",
    lblKPM: "KPM:",
    lblCPM: "CPM:",
    lblScore: "Score:",
    lblNote: "Score combines accuracy, speed, and number of correct words.",
    modalClose: "Close",
    placeholder: "Type the text above…",
    dark: "Dark",
    light: "Light",
    timeLeft: "Time Left",
    accuracy: "Accuracy",
    cpm: "CPM",
    correctWords: "Correct Words",
  },
  ar: {
    title: "تدريب الكتابة بالعربية",
    start: "ابدأ",
    next: "النص التالي",
    reset: "إعادة",
    stats: "إحصائيات",
    leaderboardTitle: "أفضل النتائج المحلية",
    leaderboardMuted: "أفضل 3 نتائج محفوظة في هذا الجهاز",
    playerPlaceholder: "اسم اللاعب",
    level_letters: "حروف — تدريب الحروف",
    level_easy: "سهل — كلمات قصيرة",
    level_medium: "متوسط — جمل قصيرة",
    level_hard: "صعب — آيات/أدعية",
    dur_60: "60 ثانية",
    dur_120: "120 ثانية",
    dur_180: "180 ثانية",
    modalTitle: "ملخص الجلسة",
    lblPlayer: "اللاعب:",
    lblLevel: "المستوى:",
    lblDuration: "المدة:",
    lblWords: "الكلمات الصحيحة:",
    lblAccuracy: "الدقة:",
    lblKPM: "كلمة/دقيقة:",
    lblCPM: "حرف/دقيقة:",
    lblScore: "النتيجة:",
    lblNote: "النتيجة تجمع الدقة والسرعة وعدد الكلمات الصحيحة.",
    modalClose: "إغلاق",
    placeholder: "اكتب النص أعلاه…",
    dark: "مظلم",
    light: "مضيء",
    timeLeft: "الوقت المتبقي",
    accuracy: "الدقة",
    cpm: "حرف/دقيقة",
    correctWords: "الكلمات الصحيحة",
  }
};

export const LS_KEYS = {
  LEADERBOARD: "arabTypingLeaderboard_v4_react",
  DARK_MODE: "arabTypingDarkMode_v2_react",
  PLAYER_NAME: "arabTypingPlayerName_v2_react",
  LANGUAGE: "arabTypingUILang_v2_react",
};
